# Generated by Django 6.0.7 on 2026-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancecheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("compliant", "Compliant"),
                    ("non_compliant", "Non-Compliant"),
                ],
                default="pending_review",
                max_length=20,
            ),
        ),
    ]
