# Generated by Django 6.0.7 on 2026-09-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_alter_compliancecheck_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecheck",
            name="waste_type",
            field=models.CharField(
                choices=[
                    ("organic", "Organic Only"),
                    ("dry", "Dry Only"),
                    ("both", "Both Types"),
                ],
                default=0,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="compliancecheck",
            name="weight_kg",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
