# Generated by Django 6.0.7 on 2026-08-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreenPointsEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compliance_check",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compliance.compliancecheck",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_entries",
                        to="households.household",
                    ),
                ),
            ],
        ),
    ]
