# Generated by Django 6.0.7 on 2026-09-10 07:49

import django.db.models.deletion
import rewards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_compliancecheck_waste_type_compliancecheck_weight_kg"),
        ("households", "0002_household_owner"),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("points_cost", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="greenpointsentry",
            name="compliance_check",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compliance.compliancecheck",
            ),
        ),
        migrations.CreateModel(
            name="Redemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_spent", models.PositiveIntegerField()),
                (
                    "voucher_code",
                    models.CharField(
                        default=rewards.models.generate_voucher_code,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="households.household",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="rewards.partneroffer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="greenpointsentry",
            name="redemption",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_entry",
                to="rewards.redemption",
            ),
        ),
        migrations.AddConstraint(
            model_name="greenpointsentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("compliance_check__isnull", False),
                        ("redemption__isnull", True),
                    ),
                    models.Q(
                        ("compliance_check__isnull", True),
                        ("redemption__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="points_entry_exactly_one_source",
            ),
        ),
    ]
